# -*- coding: utf-8 -*-
"""Semiconductor Supply Chain Shock Absorber Model Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chcD1vds0UsAHBO3QS2LKJz-vKbOeuMp
"""

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

# 1. Ingest and Format the FRED Supply Chain Data
# Ensure the filename matches your upload exactly
fred_file = 'PCU3332423332420.csv'
df_ppi = pd.read_csv(fred_file, parse_dates=['DATE'], index_col='DATE')
df_ppi.rename(columns={'PCU3332423332420': 'Semi_PPI'}, inplace=True)

# Calculate YoY change to represent the "Supply Shock" magnitude
df_ppi['PPI_Shock_YoY'] = df_ppi['Semi_PPI'].pct_change(periods=12)
# Resample to monthly to match standard equity analysis timeframes
df_ppi = df_ppi.resample('M').last()

# 2. Ingest the Yahoo Finance Equity Data
# Using the specific tickers from your provided URL configuration
tickers = ["^GSPC", "^YH31130010"]
start_date = df_ppi.index.min().strftime('%Y-%m-%d')
end_date = df_ppi.index.max().strftime('%Y-%m-%d')

print("Fetching Yahoo Finance Data...")
df_equity = yf.download(tickers, start=start_date, end=end_date)['Adj Close']
df_equity.rename(columns={'^GSPC': 'SP500', '^YH31130010': 'Semi_Index'}, inplace=True)

# If the custom Yahoo index ^YH31130010 fails to fetch via API, fallback to SMH (VanEck Semiconductor ETF)
if df_equity['Semi_Index'].isnull().all():
    print("Custom index not found via API, falling back to SMH ETF proxy...")
    df_equity['Semi_Index'] = yf.download("SMH", start=start_date, end=end_date)['Adj Close']

# Calculate monthly returns
df_equity_monthly = df_equity.resample('M').last().pct_change()

# 3. Merge Datasets
df_merged = pd.merge(df_equity_monthly, df_ppi[['PPI_Shock_YoY']], left_index=True, right_index=True, how='inner')
df_merged = df_merged.dropna()

# 4. The Shock Absorber Model (Lagged Regression)
# Shift the PPI shock forward by 3 months to test if past supply shocks predict current equity drawdowns
lag_months = 3
df_merged[f'PPI_Shock_Lag_{lag_months}M'] = df_merged['PPI_Shock_YoY'].shift(lag_months)
df_merged = df_merged.dropna()

# Define independent (X) and dependent (y) variables
X = df_merged[['SP500', f'PPI_Shock_Lag_{lag_months}M']]
X = sm.add_constant(X) # Add alpha
y = df_merged['Semi_Index']

# Fit Ordinary Least Squares (OLS) Regression
model = sm.OLS(y, X).fit()
print("\n--- Supply Chain Shock Absorber Regression Results ---")
print(model.summary())

# 5. Visualizations
sns.set_theme(style="darkgrid")
fig, axes = plt.subplots(2, 1, figsize=(14, 10), sharex=True)

# Top Plot: Equity Prices vs. Raw Supply Chain Costs
color = 'tab:blue'
axes[0].set_ylabel('Semi Index Level', color=color)
axes[0].plot(df_equity.index, df_equity['Semi_Index'], color=color, label='Semi Index')
axes[0].tick_params(axis='y', labelcolor=color)

ax2 = axes[0].twinx()
color = 'tab:red'
ax2.set_ylabel('Semiconductor Machinery PPI (Cost)', color=color)
ax2.plot(df_ppi.index, df_ppi['Semi_PPI'], color=color, linestyle='--', label='PPI Cost')
ax2.tick_params(axis='y', labelcolor=color)
axes[0].set_title('Absolute Levels: Semiconductor Equities vs. Manufacturing PPI')

# Bottom Plot: The "Shock" vs Equity Returns
axes[1].axhline(0, color='black', linewidth=1)
axes[1].plot(df_merged.index, df_merged['Semi_Index'], label='Semi Monthly Return', alpha=0.6)
axes[1].plot(df_merged.index, df_merged[f'PPI_Shock_Lag_{lag_months}M'], label=f'{lag_months}M Lagged PPI Shock (YoY)', color='red', linewidth=2)
axes[1].set_title('Rate of Change: Supply Shocks vs Equity Returns')
axes[1].legend()

plt.tight_layout()
plt.show()

# 6. Rolling Correlation Analysis
rolling_window = 24 # 2-year rolling window
rolling_corr = df_merged['Semi_Index'].rolling(window=rolling_window).corr(df_merged[f'PPI_Shock_Lag_{lag_months}M'])

plt.figure(figsize=(14, 4))
plt.plot(rolling_corr.index, rolling_corr, color='purple')
plt.axhline(0, color='black', linestyle='--')
plt.title(f'{rolling_window}-Month Rolling Correlation: Semi Returns vs. {lag_months}M Lagged Supply Shock')
plt.ylabel('Correlation Coefficient')
plt.show()

from google.colab import drive
drive.mount('/content/drive')